# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: create config file
      run: |
        echo $API_APP_KEY >> ./orange-stock-ios/orange-stock-ios/Configs/Config.xcconfig
        echo $API_APP_SECRET >> ./orange-stock-ios/orange-stock-ios/Configs/Config.xcconfig
      env:
        API_APP_KEY: ${{ secrets.API_APP_KEY }}
        API_APP_SECRET: ${{ secrets.API_APP_SECRET }}
      
    - name: Start xcode build
      run: |
        pod install --repo-update --clean-install --project-directory=orange-stock-ios/ 
        xcodebuild clean test -workspace orange-stock-ios/orange-stock-ios.xcworkspace -scheme orange-stock-ios -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=latest'
        
